In [62]:
#Load data
import random
file = open("data.txt","r")
dataVec = file.readlines()
file.close()

random.seed(1)
random.shuffle(dataVec)

Sequences = []
Labels= []
for line in dataVec:
    l = line.strip().split(",")
    Sequences.append(l[0])
    Labels.append(l[1])

In [63]:
numSequences = []
for seq in Sequences:
    new = []
    for letter in seq:
        if letter == "A":
            new.append(1)
        elif letter == "T":
            new.append(2)
        elif letter == "G":
            new.append(3)
        elif letter == "C":
            new.append(4)
            
    numSequences.append(new)

numLabels = []
for label in Labels:
    if label == "gene":
        numLabels.append(1)
    elif label == "noise":
        numLabels.append(0)
        


In [74]:
def codonindextovector(i):
    # takes value from 0 to 4, returns Vector with 1 at corresponding index
    # ex 2 -> [0, 1, 0, 0]
    # ex 0 -> [0, 0, 0, 0]
    out = [0,0,0,0]
    if i != 0:
        out[i-1] = 1
    return out

newList = []
for seq in numSequences:
    newseq = []
    for i in range(1000):
        if i < len(seq):
            newseq.append(codonindextovector(seq[i]))
        elif i >= len (seq):
            newseq.append(codonindextovector(0))
    newList.append(newseq)
            

In [75]:
print(numLabels[0:3])
print(numSequences[0:1])
print(newList[0:1])

[0, 1, 1]
[[1, 2, 3, 1, 3, 1, 3, 2, 1, 4, 4, 1, 4, 1, 1, 3, 2, 1, 2, 1, 2, 4, 1, 3, 1, 3, 1, 4, 1, 2, 2, 3, 2, 2, 1, 3]]
[[[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0], [1, 0, 0, 0], [0, 0, 1, 0], [1, 0, 0, 0], [0, 0, 1, 0], [0, 1, 0, 0], [1, 0, 0, 0], [0, 0, 0, 1], [0, 0, 0, 1], [1, 0, 0, 0], [0, 0, 0, 1], [1, 0, 0, 0], [1, 0, 0, 0], [0, 0, 1, 0], [0, 1, 0, 0], [1, 0, 0, 0], [0, 1, 0, 0], [1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 0, 1], [1, 0, 0, 0], [0, 0, 1, 0], [1, 0, 0, 0], [0, 0, 1, 0], [1, 0, 0, 0], [0, 0, 0, 1], [1, 0, 0, 0], [0, 1, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0], [0, 1, 0, 0], [0, 1, 0, 0], [1, 0, 0, 0], [0, 0, 1, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0,

In [81]:
import numpy as np

SequenceArray = np.array(newList).reshape(-1,1000,4)

In [84]:
arrayLabels = np.array(numLabels)

In [82]:
print(SequenceArray[0:2])

[[[1 0 0 0]
  [0 1 0 0]
  [0 0 1 0]
  ...
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[1 0 0 0]
  [0 1 0 0]
  [0 0 1 0]
  ...
  [0 1 0 0]
  [0 0 0 1]
  [0 0 1 0]]]


In [99]:
import tensorflow as tf

model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Flatten())
#model.add(tf.keras.Input(shape = (1000,4)))
model.add(tf.keras.layers.Dense(128, activation=tf.nn.relu))
model.add(tf.keras.layers.Dense(128, activation=tf.nn.relu))
model.add(tf.keras.layers.Dense(2, activation=tf.nn.softmax))

model.compile(optimizer='adam',loss='sparse_categorical_crossentropy',metrics=['accuracy'])
model.fit(SequenceArray, arrayLabels, epochs=5)


Train on 11356 samples
Epoch 1/5
11356/11356 [==============================] - 3s 298us/sample - loss: 0.2637 - accuracy: 0.9078
Epoch 2/5
11356/11356 [==============================] - 3s 227us/sample - loss: 0.1934 - accuracy: 0.9259
Epoch 3/5
11356/11356 [==============================] - 3s 230us/sample - loss: 0.1410 - accuracy: 0.9468
Epoch 4/5
11356/11356 [==============================] - 3s 223us/sample - loss: 0.0905 - accuracy: 0.9679
Epoch 5/5
11356/11356 [==============================] - 2s 220us/sample - loss: 0.0595 - accuracy: 0.9790
